mysql:
  charset: utf8
  db: gggo
  host: localhost
  password: schoollzc1
  user: root
server:
  port: 8888
  log: "run/server.log"
  pid: "run/server.pid"
  watch_path:
    - "./server.go"
    - "./watch.go"
