mysql:
  charset: utf8
  db: gggo
  host: localhost
  password: schoollzc1
  user: root
server:
  port: 8889
  log: "run/server.log"
  pid: "run/server.pid"
  watch_path:
    - "../config.yml"
    - "./server.go"
    - "./watch.go"
    - "./templates"
    - "./templates/index"
    - "./vm"
    - "./controller"
    - "./model"
